Vaurca Stuff
CrowOfBourbon/NMF-Persephone pull request #91
Opened 2022-03-28 16:27 UTC by Dekserrrrrr

-Adds new Vaurca accents
-Adds the grounds for a new Vaurca subspecies
-Adjusts Vaurca stats, heavily
-Adds custom biometrics to Vaurcae
-Moves Vaurcae organs around, primarily, putting the brain in the chest

2022-03-28 16:39 UTC, remona-minett commented
Reported: Bug making humans unselectable

2022-03-30 09:10 UTC, Dekserrrrrr commented
Accents are still fucky, we'll sort it out later. I'm tired and want this PR to be over. Good to merge, bug accents aren't in yet.

2022-03-30 13:29 UTC, remona-minett commented
We expressly state we are not willing to merge incomplete or otherwise buggy/experimental PRs, and this is included in it. Once your accents are either removed entirely (all bugged code) or made to work, we can merge this.

We will not merge known bad code.

2022-03-30 13:30 UTC, remona-minett requested changes
All bugged code must be removed.

2022-03-30 13:30 UTC, ghost commented on code/modules/mob/living/carbon/human/species/station/vaurca/vaurca_subspecies.dm
> +	speech_chance = 100
This will get annoying fast

2022-03-30 18:36 UTC, Dekserrrrrr commented
Code was always BUGged, but never affects the players in-game.

2022-04-11 19:58 UTC, remona-minett commented
Once you fix the conflicts and mark it ready for review, someone can look at this.

2023-07-22 08:43 UTC, closed without merging